//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/protagoniste/carte_de_control.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Carte_de_control : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Carte_de_control()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""carte_de_control"",
    ""maps"": [
        {
            ""name"": ""control"",
            ""id"": ""96d81ac0-3903-41ef-a9b6-7f69fd7452fc"",
            ""actions"": [
                {
                    ""name"": ""testaction"",
                    ""type"": ""Button"",
                    ""id"": ""7ee2ba8f-2476-4574-8699-77b9b2c611f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""70a04157-e964-4c9f-a71b-7a220291e32c"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""testaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // control
        m_control = asset.FindActionMap("control", throwIfNotFound: true);
        m_control_testaction = m_control.FindAction("testaction", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // control
    private readonly InputActionMap m_control;
    private IControlActions m_ControlActionsCallbackInterface;
    private readonly InputAction m_control_testaction;
    public struct ControlActions
    {
        private @Carte_de_control m_Wrapper;
        public ControlActions(@Carte_de_control wrapper) { m_Wrapper = wrapper; }
        public InputAction @testaction => m_Wrapper.m_control_testaction;
        public InputActionMap Get() { return m_Wrapper.m_control; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlActions set) { return set.Get(); }
        public void SetCallbacks(IControlActions instance)
        {
            if (m_Wrapper.m_ControlActionsCallbackInterface != null)
            {
                @testaction.started -= m_Wrapper.m_ControlActionsCallbackInterface.OnTestaction;
                @testaction.performed -= m_Wrapper.m_ControlActionsCallbackInterface.OnTestaction;
                @testaction.canceled -= m_Wrapper.m_ControlActionsCallbackInterface.OnTestaction;
            }
            m_Wrapper.m_ControlActionsCallbackInterface = instance;
            if (instance != null)
            {
                @testaction.started += instance.OnTestaction;
                @testaction.performed += instance.OnTestaction;
                @testaction.canceled += instance.OnTestaction;
            }
        }
    }
    public ControlActions @control => new ControlActions(this);
    public interface IControlActions
    {
        void OnTestaction(InputAction.CallbackContext context);
    }
}
